FROM ubuntu as builder

WORKDIR /opt/app

COPY package.json /opt/app/package.json

RUN apt-get update && apt-get install -y curl
RUN curl -fsSL https://deb.nodesource.com/setup_20.x  | bash -
RUN apt install -y nodejs
RUN node -v

RUN npm install

COPY . /opt/app

RUN npm run build

FROM nginx

COPY --from=builder /opt/app/dist /usr/share/nginx/html